name: coffeematch-v1.0
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12

  # Shared libraries
  - pandas
  - numpy
  - openpyxl
  - pylint

  # Streamlit stack
  - streamlit>=1.18
  - altair>=4.2,<5


