name: coffeematch-v1.0
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.12

  # Shared libraries
  - pandas
  - numpy
  - matplotlib
  - openpyxl
  - pylint=4.0.5
  - seaborn
  - sodapy=2.2.0

  # Streamlit stack
  - streamlit>=1.18
  - altair>=4.2,<5
  - pip:
    - coverage==7.13


