"""This is the testing module for the address API script and it
relies upon imports from that script as well as the load.py
module. Two Edge tests of coffees that will thrown the output
into disorganization and three oneshot tests to confirm correct
output of a successsuccessful full API call and an unsuccessful
 one, and finally the total number of coffees from load.py."""

#note that the 80% of load.py not "covered" as coverage, are
#actually meant to trigger tests in test_load.py.

import unittest
import numpy as np
import pandas as pd

from scripts.address import cafe_override, freq_roasters, county_api_call
from scripts.load import load_products


PRODUCTS_PATH = "data/raw/Product_Information_archive.xlsx"

class EdgeTestAddressType(unittest.TestCase):
    """EdgeTest 1 of 2 for the address.py file"""
    def test_check_miss_match(self):
        """This test ensures that when a dataframe of a different shape than
        what would be expected from the original Product_Information.xlsx
        file is used on the address.py script that it produces a type error."""
        d = {"roaster": ["Anchorhead Coffee", "Blossom Coffee Roasters", "Caffe Vita", "Bob's"],
         "no_of_roasters": pd.Series([0, 1, 2, 3], index=[0,1,2, 3])}
        roast_test = pd.DataFrame(data=d, index=[0, 1, 2, 3])
        with self.assertRaises(TypeError):
            cafe_override(roast_test)
suite = unittest.TestLoader().loadTestsFromTestCase(EdgeTestAddressType)
_ = unittest.TextTestRunner().run(suite)




class EdgeTestAddressValue(unittest.TestCase):
    """EdgeTest2 of 2."""
    def test_check_miss_match(self):
        """This test ensures that when a dataframe having a different value 
        in the 10th position of a summary generated by the original 
        Product_Information.xlsx file is used on the address.py script
        that it produces a values error."""
        f = {"roaster": ['ANCHORHEAD COFFE', 'Blossom Coffe Roasters','CAFE VITA',
         'Camber Coffe', 'Kuma Coffe', 'CAFE LADRO', 'OLYMPIA COFFE',
         'OLYMPIA COFFE', 'SEVEN COFFE ROASTERS MARKET & CAFE', 'LITLE JAYE',
         "X", 'Tonys Coffe','VICTROLA COFFE','VICTROLA COFFE'],
          "no_of_roasters": pd.Series(list(range(14)), index=list(range(14)))}
        roast_test_2 = pd.DataFrame(data=f, index=list(range(14)))
        with self.assertRaises(ValueError):
            cafe_override(roast_test_2)
suite = unittest.TestLoader().loadTestsFromTestCase(EdgeTestAddressValue)
_ = unittest.TextTestRunner().run(suite)




class OneShotTest(unittest.TestCase):
    """One shot test one success api call"""
    def test_success_one(self):
        """This confirms that the the number of packages of coffee present in the
        the file is the expected 248."""
        check_one=sum(freq_roasters(load_products(PRODUCTS_PATH))['no_of_roasters'])
        self.assertTrue(np.isclose(check_one,248,atol=1e-05))
suite = unittest.TestLoader().loadTestsFromTestCase(OneShotTest)
_ = unittest.TextTestRunner().run(suite)




class OneShotTest2(unittest.TestCase):
    """One shot test two handle """
    def test_success_two(self):
        """This confirms that CAFE VITA returns that name from the API search excising the
        function county_api_call"""
        check_vita=['CAFFE VITA']
        #the sum of the api call result matching the name given should be 1
        result=county_api_call(check_vita)
        self.assertTrue(np.isclose(sum(result['cafe_name']==check_vita),1,atol=1e-05))
suite = unittest.TestLoader().loadTestsFromTestCase(OneShotTest2)
_ = unittest.TextTestRunner().run(suite)



class OneShotTest3(unittest.TestCase):
    """One shot test three"""
    def test_success_two(self):
        """This confirms that there's no coffee shop named aza yet at King
        County inspections."""
        check_aza=['aza']
        result=county_api_call(check_aza)
        check_three=sum(result['cafe_name']=='No_cafe_identified_in_King')
        self.assertTrue(np.isclose(check_three,1,atol=1e-05))
suite = unittest.TestLoader().loadTestsFromTestCase(OneShotTest3)
_ = unittest.TextTestRunner().run(suite)




print('End of testing')


if __name__ == '__main__':
    unittest.main()
