"""
Recommendation engine for CoffeeMatch.

This module filters, scores, and ranks coffee products using the
product-level feature table generated by feature_engineering.py.

Design principles
-----------------
- Recommendations are made at the product level.
- Size rows are used only to build available size options for display.
- Filtering is applied before ranking when the user expresses hard
  requirements such as decaf or ground availability.
- Ranking combines roast match, value, and popularity signals.
- Output is returned as Recommendation dataclass objects for the UI.
"""

from __future__ import annotations

import math
import pandas as pd

from .schemas import (
    Recommendation, UserPreferences, 
    SizeOption, CafeLocation, ReviewData
)


RECOMMENDATION_REQUIRED_COLUMNS = (
    "product_key",
    "roaster",
    "product_name",
    "origin",
    "roast_type",
    "decaf",
    "blend",
    "single_origin",
    "available_ground",
    "url",
    "has_reviews",
    "total_reviews",
    "heart_percentage",
    "roast_light",
    "roast_medium",
    "roast_dark",
    "roast_unknown",
    "reference_price_per_oz",
    "reference_size_label",
    "reference_size_oz",
    "reference_price_numeric",
    "reference_size_tier",
    "value_signal",
    "review_strength",
)

SIZE_OPTION_REQUIRED_COLUMNS = (
    "product_key",
    "size",
    "size_oz",
    "price_numeric",
    "price_per_oz",
)


def validate_recommendation_columns(feature_table: pd.DataFrame) -> None:
    """
    Validate that all required recommendation columns exist.

    Parameters
    ----------
    feature_table : pd.DataFrame
        Product-level feature table.

    Raises
    ------
    ValueError
        If one or more required columns are missing.
    """
    missing_columns = sorted(
        set(RECOMMENDATION_REQUIRED_COLUMNS) - set(feature_table.columns)
    )
    if missing_columns:
        missing_str = ", ".join(missing_columns)
        raise ValueError(
            "Feature table is missing required recommendation columns: "
            f"{missing_str}"
        )


def validate_size_option_columns(products_df: pd.DataFrame) -> None:
    """
    Validate that the size-level products dataset has the columns needed
    to build SizeOption objects.

    Parameters
    ----------
    products_df : pd.DataFrame
        Size-level processed products dataset.

    Raises
    ------
    ValueError
        If one or more required columns are missing.
    """
    missing_columns = sorted(set(SIZE_OPTION_REQUIRED_COLUMNS) - set(products_df.columns))
    if missing_columns:
        missing_str = ", ".join(missing_columns)
        raise ValueError(
            "Products data is missing required size option columns: "
            f"{missing_str}"
        )


def filter_products(feature_table: pd.DataFrame, preferences: UserPreferences,) -> pd.DataFrame:
    """
    Apply hard user requirements before ranking.

    Parameters
    ----------
    feature_table : pd.DataFrame
        Product-level feature table.
    preferences : UserPreferences
        User selections from the UI.

    Returns
    -------
    pd.DataFrame
        Filtered product-level feature table.
    """
    # pylint: disable=singleton-comparison
    filtered_df = feature_table.copy()

    if preferences.decaf is not None:
        filtered_df = filtered_df[filtered_df["decaf"] == preferences.decaf]

    if preferences.ground_required:
        filtered_df = filtered_df[filtered_df["available_ground"] == True]  # noqa: E712

    if preferences.single_origin_preference is True:
        filtered_df = filtered_df[filtered_df["single_origin"] == True]  # noqa: E712

    if preferences.blend_preference is True:
        filtered_df = filtered_df[filtered_df["blend"] == True]  # noqa: E712

    if preferences.max_price_per_oz is not None:
        filtered_df = filtered_df[
            filtered_df["reference_price_per_oz"] <= preferences.max_price_per_oz
        ]

    return filtered_df.reset_index(drop=True)


def get_roast_preference_columns(roast_type: str | None) -> list[str]:
    """
    Map a user roast preference to the corresponding overlap-aware roast
    membership columns.

    Parameters
    ----------
    roast_type : str | None
        Roast preference from the UI.

    Returns
    -------
    list[str]
        Roast membership columns that count as a match.
    """
    if roast_type is None:
        return []

    normalized = roast_type.strip().lower()

    if normalized == "no preference":
        return []

    mapping = {
        "light": ["roast_light"],
        "medium": ["roast_medium"],
        "dark": ["roast_dark"],
    }

    return mapping.get(normalized, [])


def compute_roast_match_scores(feature_table: pd.DataFrame,
    preferences: UserPreferences,
) -> pd.Series:
    """
    Compute roast match scores in the range [0, 1].

    Parameters
    ----------
    feature_table : pd.DataFrame
        Product-level feature table.
    preferences : UserPreferences
        User selections from the UI.

    Returns
    -------
    pd.Series
        Roast match scores aligned to feature_table index.
    """
    if preferences.roast_type is None:
        return pd.Series(1.0, index=feature_table.index, dtype=float)

    preferred_columns = get_roast_preference_columns(preferences.roast_type)
    if not preferred_columns:
        return pd.Series(1.0, index=feature_table.index, dtype=float)

    roast_match = feature_table[preferred_columns].max(axis=1).astype(float)
    return roast_match


def min_max_scale(values: pd.Series) -> pd.Series:
    """
    Min-max scale a numeric series to [0, 1].

    If all values are identical, return 1.0 for all non-missing values.
    Missing values are treated as 0.

    Parameters
    ----------
    values : pd.Series
        Numeric values to scale.

    Returns
    -------
    pd.Series
        Scaled values.
    """
    clean_values = values.fillna(0).astype(float)
    min_value = clean_values.min()
    max_value = clean_values.max()

    if math.isclose(min_value, max_value):
        return pd.Series(1.0, index=clean_values.index, dtype=float)

    return (clean_values - min_value) / (max_value - min_value)


def compute_component_scores(
    feature_table: pd.DataFrame,
    preferences: UserPreferences,
) -> pd.DataFrame:
    """
    Compute roast, value, popularity, and final recommendation scores.

    Parameters
    ----------
    feature_table : pd.DataFrame
        Filtered product-level feature table.
    preferences : UserPreferences
        User selections from the UI.

    Returns
    -------
    pd.DataFrame
        Copy of feature_table with score columns added.
    """
    scored_df = feature_table.copy()

    scored_df["roast_match_score"] = compute_roast_match_scores(scored_df, preferences)
    scored_df["value_score"] = min_max_scale(scored_df["value_signal"])
    scored_df["popularity_score"] = min_max_scale(scored_df["review_strength"])

    total_weight = (
        preferences.roast_weight
        + preferences.price_weight
        + preferences.popularity_weight
    )

    if total_weight <= 0:
        raise ValueError("Recommendation weights must sum to a positive value.")

    roast_weight = preferences.roast_weight / total_weight
    price_weight = preferences.price_weight / total_weight
    popularity_weight = preferences.popularity_weight / total_weight

    scored_df["score"] = (
        roast_weight * scored_df["roast_match_score"]
        + price_weight * scored_df["value_score"]
        + popularity_weight * scored_df["popularity_score"]
    )

    return scored_df


def sort_recommendations(scored_df: pd.DataFrame) -> pd.DataFrame:
    """
    Sort recommendations from strongest to weakest.

    Parameters
    ----------
    scored_df : pd.DataFrame
        Product-level feature table with score columns.

    Returns
    -------
    pd.DataFrame
        Sorted recommendations.
    """
    sorted_df = scored_df.sort_values(
        by=[
            "score",
            "roast_match_score",
            "value_score",
            "popularity_score",
            "total_reviews",
            "product_name",
        ],
        ascending=[False, False, False, False, False, True],
    )
    return sorted_df.reset_index(drop=True)


def build_size_options(products_df: pd.DataFrame) -> dict[str, list[SizeOption]]:
    """
    Build size option objects grouped by product_key.

    Parameters
    ----------
    products_df : pd.DataFrame
        Size-level processed products dataset.

    Returns
    -------
    dict[str, list[SizeOption]]
        Mapping from product_key to available size options.
    """
    size_options_by_product: dict[str, list[SizeOption]] = {}

    sorted_products = products_df.sort_values(
        by=["product_key", "size_oz", "price_numeric"],
        ascending=[True, True, True],
    )

    for product_key, group in sorted_products.groupby("product_key"):
        size_options: list[SizeOption] = []

        for _, row in group.iterrows():
            size_option = SizeOption(
                size=str(row["size"]),
                size_oz=float(row["size_oz"]),
                price_numeric=float(row["price_numeric"]),
                price_per_oz=float(row["price_per_oz"]),
            )
            size_options.append(size_option)

        size_options_by_product[product_key] = size_options

    return size_options_by_product

def is_washington_zip(zip_code: str | None) -> bool:
    """Return True if the ZIP code falls within Washington state range."""
    if zip_code is None:
        return False

    try:
        zip_int = int(zip_code)
    except (ValueError, TypeError):
        return False

    return 98000 <= zip_int <= 99499
    

def build_product_info_lookup(product_info_df: pd.DataFrame) -> dict[str, CafeLocation]:
    """
    Build a lookup table of cafe location information by product key.

    Parameters
    ----------
    product_info_df : pd.DataFrame
        Dataset containing cafe location information associated
        with coffee products.

    Returns
    -------
    dict[str, CafeLocation]
        Mapping from product_key to a CafeLocation object containing
        cafe name, address, city, state, zip code, coordinates, and
        optional Google Maps URL.
    """
    product_info_lookup: dict[str, CafeLocation] = {}

    for _, row in product_info_df.iterrows():
        product_key = str(row["product_key"])

        cafe_name = None if pd.isna(row.get("cafe_name")) else str(row.get("cafe_name"))
        cafe_address = None if pd.isna(row.get("cafe_address")) else str(row.get("cafe_address"))
        cafe_city = None if pd.isna(row.get("cafe_city")) else str(row.get("cafe_city"))
        zip_code = None if pd.isna(row.get("zip_code")) else str(row.get("zip_code"))
        longitude = None if pd.isna(row.get("longitude")) else float(row.get("longitude"))
        latitude = None if pd.isna(row.get("latitude")) else float(row.get("latitude"))

        state = "WA" if is_washington_zip(zip_code) else None

        google_maps_url = None
        if latitude is not None and longitude is not None:
            google_maps_url = f"https://www.google.com/maps?q={latitude},{longitude}"

        product_info_lookup[product_key] = CafeLocation(
            cafe_name=cafe_name,
            cafe_address=cafe_address,
            cafe_city=cafe_city,
            state=state,
            zip_code=zip_code,
            longitude=longitude,
            latitude=latitude,
            google_maps_url=google_maps_url,
        )

    return product_info_lookup


def build_reviews_lookup(reviews_df: pd.DataFrame) -> dict[str, ReviewData]:
    """
    Build a lookup table of review information by product name.

    Parameters
    ----------
    reviews_df : pd.DataFrame
        Cleaned reviews dataset containing tasting notes and review
        text associated with each product.

    Returns
    -------
    dict[str, ReviewData]
        Mapping from product_name to a ReviewData object containing
        aggregated tasting notes and review texts for that product.
    """
    reviews_lookup: dict[str, ReviewData] = {}

    for product_name, group in reviews_df.groupby("product_name"):
        tasting_notes = (
            group["tasting_notes"]
            .dropna()
            .astype(str)
            .tolist()
        )

        review_texts = (
            group["review_text"]
            .dropna()
            .astype(str)
            .tolist()
        )

        reviews_lookup[str(product_name)] = ReviewData(
            tasting_notes=tasting_notes,
            review_texts=review_texts,
        )

    return reviews_lookup


def build_match_reasons(
    row: pd.Series,
    preferences: UserPreferences,
) -> list[str]:
    """
    Build simple human-readable reasons for a recommendation.

    Parameters
    ----------
    row : pd.Series
        One scored product row.
    preferences : UserPreferences
        User selections from the UI.

    Returns
    -------
    list[str]
        Explanation snippets for the recommendation.
    """
    reasons: list[str] = []

    if preferences.roast_type is not None and row["roast_match_score"] > 0:
        reasons.append(f"Matches your roast preference for {preferences.roast_type}")

    if row["value_score"] >= 0.67:
        reference_label = row.get("reference_size_label")
        if pd.notna(reference_label):
            reasons.append(
                f"Strong value based on its {reference_label} reference bag"
            )
        else:
            reasons.append("Strong value compared with similar products")

    if row["popularity_score"] >= 0.67 and row.get("has_reviews", False):
        total_reviews = row.get("total_reviews")
        if pd.notna(total_reviews) and total_reviews > 0:
            reasons.append(f"Strong popularity signal from {int(total_reviews)} reviews")
        else:
            reasons.append("Strong popularity signal")

    if preferences.decaf is True and row.get("decaf") is True:
        reasons.append("Matches your decaf preference")

    if preferences.ground_required is True and row.get("available_ground") is True:
        reasons.append("Available in ground form")

    if preferences.single_origin_preference is True and row.get("single_origin") is True:
        reasons.append("Matches your single-origin preference")

    if preferences.blend_preference is True and row.get("blend") is True:
        reasons.append("Matches your blend preference")

    return reasons[:3]


def build_recommendation_objects(
    scored_df: pd.DataFrame,
    size_options_by_product: dict[str, list[SizeOption]],
    reviews_lookup: dict[str, ReviewData],
    product_info_lookup: dict[str, CafeLocation],
    ) -> list[Recommendation]:
    """
    Convert scored product rows into Recommendation dataclass objects.

    Parameters
    ----------
    scored_df : pd.DataFrame
        Sorted product-level feature table containing computed scores
        and metadata for recommended products.

    size_options_by_product : dict[str, list[SizeOption]]
        Mapping from product_key to available size options.

    reviews_lookup : dict[str, ReviewData]
        Mapping from product_name to ReviewData containing tasting
        notes and review texts for that product.

    product_info_lookup : dict[str, CafeLocation]
        Mapping from product_key to CafeLocation containing cafe
        location details associated with a product.

    Returns
    -------
    list[Recommendation]
        Final recommendation objects ready for consumption by the UI.
    """

    recommendations: list[Recommendation] = []

    for _, row in scored_df.iterrows():
        product_key = str(row["product_key"])
        product_name = str(row["product_name"])

        review_data = reviews_lookup.get(product_name, ReviewData())
        cafe_location = product_info_lookup.get(product_key)

        recommendation = Recommendation(
            product_key=product_key,
            roaster=str(row["roaster"]),
            product_name=str(row["product_name"]),
            origin=None if pd.isna(row["origin"]) else str(row["origin"]),
            roast_type=None if pd.isna(row["roast_type"]) else str(row["roast_type"]),
            decaf=None if pd.isna(row["decaf"]) else bool(row["decaf"]),
            blend=None if pd.isna(row["blend"]) else bool(row["blend"]),
            single_origin=(
                None if pd.isna(row["single_origin"]) else bool(row["single_origin"])
            ),
            available_ground=(
                None if pd.isna(row["available_ground"]) else bool(row["available_ground"])
            ),

            # Reference value used for ranking
            reference_price_per_oz=(
                None
                if pd.isna(row["reference_price_per_oz"])
                else float(row["reference_price_per_oz"])
            ),

            # Reference bag metadata
            reference_size_label=(
                None
                if pd.isna(row["reference_size_label"])
                else str(row["reference_size_label"])
            ),
            reference_size_oz=(
                None
                if pd.isna(row["reference_size_oz"])
                else float(row["reference_size_oz"])
            ),
            reference_price_numeric=(
                None
                if pd.isna(row["reference_price_numeric"])
                else float(row["reference_price_numeric"])
            ),
            reference_size_tier=(
                None
                if pd.isna(row["reference_size_tier"])
                else str(row["reference_size_tier"])
            ),

            score=float(row["score"]),
            match_reasons=row["match_reasons"],

            available_sizes=size_options_by_product.get(product_key, []),

            total_reviews=(
                None if pd.isna(row["total_reviews"]) else int(row["total_reviews"])
            ),
            heart_percentage=(
                None
                if pd.isna(row["heart_percentage"])
                else float(row["heart_percentage"])
            ),
            has_reviews=None if pd.isna(row["has_reviews"]) else bool(row["has_reviews"]),

            tasting_notes=review_data.tasting_notes,
            review_texts=review_data.review_texts,
            cafe_location=cafe_location,
        )

        recommendations.append(recommendation)

    return recommendations


def recommend_products(
    feature_table: pd.DataFrame,
    products_df: pd.DataFrame,
    reviews_df: pd.DataFrame,
    product_info_df: pd.DataFrame,
    preferences: UserPreferences,
    top_n: int = 5,
) -> list[Recommendation]:
    """
    Generate top product recommendations for the user.

    Parameters
    ----------
    feature_table : pd.DataFrame
        Product-level feature table generated in feature_engineering.py.
        Each row represents a unique product with engineered features
        used for scoring and ranking.

    products_df : pd.DataFrame
        Size-level processed products dataset used to build available
        size options for the UI. This table may contain multiple rows
        per product (one per bag size).

    reviews_df : pd.DataFrame
        Cleaned reviews dataset containing tasting notes and review
        text associated with each product.

    product_info_df : pd.DataFrame
        Cafe/location dataset providing cafe name, address, city,
        zip code, and geographic coordinates associated with a product.

    preferences : UserPreferences
        User selections captured from the UI, including roast preference,
        price sensitivity, grind options, grind format availability,
        and other filters used during scoring.

    top_n : int, default=5
        Number of recommendations to return.

    Returns
    -------
    list[Recommendation]
        Ranked recommendation objects containing product metadata,
        available size options, match reasons, aggregated review
        information, and optional cafe location details for UI display.
    """
    reviews_lookup = build_reviews_lookup(reviews_df)
    product_info_lookup = build_product_info_lookup(product_info_df)

    validate_recommendation_columns(feature_table)
    validate_size_option_columns(products_df)

    filtered_df = filter_products(feature_table, preferences)
    if filtered_df.empty:
        return []

    scored_df = compute_component_scores(filtered_df, preferences)
    scored_df = sort_recommendations(scored_df).head(top_n).copy()

    scored_df["match_reasons"] = scored_df.apply(
        build_match_reasons,
        axis=1,
        preferences=preferences,
    )

    size_options_by_product = build_size_options(products_df)

    return build_recommendation_objects(
    scored_df,
    size_options_by_product,
    reviews_lookup,
    product_info_lookup,
    )
